### ISSUE TITLE
Logstash fails to load amzon es plugin

### ISSUE THREAD

**Issue by alexandernajafi** [awslabs/logstash-output-amazon_es#105]
I have Logstash 6.4.1 (also tested 6.4.0) And is running plugin version 6.4.0. I get the following when I start logstash (dockerized logstash).

`
[2018-09-28T17:08:33,707][ERROR][logstash.pipeline        ] Error registering plugin {:pipeline_id=>".monitoring-logstash", :plugin=>"#<LogStash::OutputDelegator:0x5c8327b1>", :error=>"undefined method 'credentials' for nil:NilClass", :thread=>"#<Thread:0x7aeab79b run>"}
[2018-09-28T17:08:33,717][ERROR][logstash.pipeline        ] Pipeline aborted due to error {:pipeline_id=>".monitoring-logstash", :exception=>#<NoMethodError: undefined method 'credentials' for nil:NilClass>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-core-2.11.104/lib/aws-sdk-core/signers/v4.rb:45:in 'initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client/manticore_adapter.rb:111:in 'perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client/pool.rb:291:in 'perform_request_to_url'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client/pool.rb:245:in 'block in healthcheck!'", "org/jruby/RubyHash.java:1343:in 'each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client/pool.rb:241:in 'healthcheck!'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client/pool.rb:341:in 'update_urls'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client/pool.rb:71:in 'start'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client.rb:316:in 'build_pool'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client.rb:66:in 'initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client_builder.rb:108:in 'create_http_client'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client_builder.rb:98:in 'build'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es.rb:253:in 'build_client'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/common.rb:25:in 'register'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:102:in 'register'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:46:in 'register'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:241:in 'register_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:252:in 'block in register_plugins'", "org/jruby/RubyArray.java:1734:in 'each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:252:in 'register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:593:in 'maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:262:in 'start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:199:in 'run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:159:in 'block in start'"], :thread=>"#<Thread:0x7aeab79b run>"}
`

**Comment by crisidev** [comment]
The issue here is that you are using a relative path for the template:
```
[logstash.outputs.elasticsearch] Installing amazon_es template to _template/logstash [2018-09-28T17:03:23,567][WARN ][logstash.outputs.elasticsearch] UNEXPECTED POOL ERROR {:e=>#<URI::InvalidComponentError: bad component(expected absolute path component): _template/logstash>} [2018-09-28T17:03:23,581][ERROR][logstash.outputs.elasticsearch] Failed to install template. {:message=>"bad component(expected absolute path component): 
```

Do you mind to try to use the absolute path?

**Comment by alexandernajafi** [comment]
Thanks, I have not defined any template at all. I'll try to define it using an absolute path.

**Comment by alexandernajafi** [comment]
Hm, I still get it. First I see 
`[2018-09-28T17:16:23,273][INFO ][logstash.outputs.elasticsearch] Using mapping template from {:path=>"/opt/template.json"}`

And then I get the same message
``[2018-09-28T17:16:23,579][ERROR][logstash.outputs.elasticsearch] Failed to install template. {:message=>"bad component(expected absolute path component): `

**Comment by jstop** [comment]
`[logstash.outputs.elasticsearch] Installing amazon_es template to _template/logstash [2018-09-28T17:03:23,567][WARN ][logstash.outputs.elasticsearch] UNEXPECTED POOL ERROR {:e=>#<URI::InvalidComponentError: bad component(expected absolute path component): _template/logstash>} [2018-09-28T17:03:23,581][ERROR][logstash.outputs.elasticsearch] Failed to install template. {:message=>"bad component(expected absolute path component): 
`
This error happens without an override value for template. The fix is described in this issue https://github.com/awslabs/logstash-output-amazon_es/issues/101

**Comment by StevenRomeo** [comment]
The version of the plugin pulled down using the logstash-plugin install utility still has this bug however it's been fixed in the master branch. I cloned master, created a gem, and loaded the gem using _logstash-plugin install_ and there is no longer an issue.

**Comment by jpuskar** [comment]
@StevenRomeo,
I'm struggling to get this gem created. Would you mind commenting how you did it?

**Comment by Alien2150** [comment]
@jpuskar can send you a running docker image in 2-3 hours

**Comment by Alien2150** [comment]
@jpuskar here we go:

```
 FROM jruby:9-alpine

VOLUME /var/build_dir
WORKDIR /var/build_dir
RUN gem install bundler

ENTRYPOINT ["gem"]
CMD [ "build", "logstash-output-amazon_es.gemspec" ]
```

**Comment by musabqamri123** [comment]
this latest version 6.4.1 is not yet published on https://rubygems.org/gems/logstash-output-amazon_es

**Comment by crisidev** [comment]
We published version 6.4.1, which should solve the template path issue reported here. Do you mind to try the latest version to see if it fixes your issue?

**Comment by musabqamri123** [comment]
Thanks.. This fixed the issue.

**Comment by crisidev** [comment]
Ok. I will close this issue. Thanks for getting back to us.
