### ISSUE TITLE
When run the logstash using the service it fail to send data to aws elasticsearch

### ISSUE THREAD

**Issue by cpanato** [awslabs/logstash-output-amazon_es#34]
Hello

When I use the following command to start logstash and send data to AWS elasticsearch it works:

`sudo /opt/logstash/bin/logstash -f /etc/logstash/conf.d/01-logstash.conf`

however when I use the following command:

`sudo service logstash start`

I got some errors like:

> {:timestamp=>"2016-06-14T14:17:35.040000+0000", :message=>"Attempted to send a bulk request to Elasticsearch configured at '[\"https://mhxqojiy.us-west.es.amazonaws.com:443\"]', but an error occurred and it failed! Are you sure you can reach elasticsearch from this machine using the configuration provided?", :client_config=>{:hosts=>["https://jiy.us-west.es.amazonaws.com:443"], :region=>"us-west-1", :aws_access_key_id=>nil, :aws_secret_access_key=>nil, :transport_options=>{:request=>{:open_timeout=>0, :timeout=>60}, :proxy=>nil}, :transport_class=>Elasticsearch::Transport::Transport::HTTP::AWS, :logger=>nil, :tracer=>nil, :reload_connections=>false, :retry_on_failure=>false, :reload_on_failure=>false, :randomize_hosts=>false, :http=>{:scheme=>"https", :user=>nil, :password=>nil, :port=>443}}, :error_message=>"undefined method `credentials' for nil:NilClass", :error_class=>"NoMethodError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.1.36/lib/aws-sdk-core/signers/v4.rb:24:in`initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es/aws_v4_signer_impl.rb:36:in `signer'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es/aws_v4_signer_impl.rb:48:in`call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in`run_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es/aws_transport.rb:49:in `perform_request'", "org/jruby/RubyProc.java:281:in`call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.17/lib/elasticsearch/transport/transport/base.rb:257:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es/aws_transport.rb:45:in`perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.17/lib/elasticsearch/transport/client.rb:128:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.17/lib/elasticsearch/api/actions/bulk.rb:88:in`bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es/http_client.rb:53:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es.rb:322:in`submit'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es.rb:319:in`submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es.rb:352:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in`buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in`buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:159:in `buffer_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es.rb:312:in`receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/outputs/base.rb:83:in `multi_receive'", "org/jruby/RubyArray.java:1613:in`each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/outputs/base.rb:83:in `multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/output_delegator.rb:130:in`worker_multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/output_delegator.rb:114:in `multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:301:in`output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:301:in`output_batch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:232:in `worker_loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:201:in`start_workers'"], :level=>:error}

Version: logstash 2.3.2

Can you guys faced it?
thanks!

**Comment by ctadeu** [comment]
> {:timestamp=>"2016-06-14T14:25:01.619000+0000", :message=>"Failed to install template: undefined method `credentials' for nil:NilClass", :level=>:error}
{:timestamp=>"2016-06-14T14:25:02.382000+0000", :message=>"Pipeline main started"}
{:timestamp=>"2016-06-14T14:25:02.897000+0000", :message=>"Attempted to send a bulk request to Elasticsearch configured at '[\"https://search-bi-clm-nuz74vnbadur5amhixowxqojiy.us-west-2.es.amazonaws.com:443\"]', but an error occurred and it failed! Are you sure you can reach elasticsearch from this machine using the configuration provided?", :client_config=>{:hosts=>["https://search-bi-clm-nuz74vnbadur5amhixowxqojiy.us-west-2.es.amazonaws.com:443"], :region=>"us-west-2", :aws_access_key_id=>nil, :aws_secret_access_key=>nil, :transport_options=>{:request=>{:open_timeout=>0, :timeout=>60}, :proxy=>nil}, :transport_class=>Elasticsearch::Transport::Transport::HTTP::AWS, :logger=>nil, :tracer=>nil, :reload_connections=>false, :retry_on_failure=>false, :reload_on_failure=>false, :randomize_hosts=>false, :http=>{:scheme=>"https", :user=>nil, :password=>nil, :port=>443}}, :error_message=>"undefined method `credentials' for nil:NilClass", :error_class=>"NoMethodError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.1.36/lib/aws-sdk-core/signers/v4.rb:24:in `initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es/aws_v4_signer_impl.rb:36:in `signer'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es/aws_v4_signer_impl.rb:48:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es/aws_transport.rb:49:in `perform_request'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.17/lib/elasticsearch/transport/transport/base.rb:257:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es/aws_transport.rb:45:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.17/lib/elasticsearch/transport/client.rb:128:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.17/lib/elasticsearch/api/actions/bulk.rb:88:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es/http_client.rb:53:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es.rb:322:in `submit'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es.rb:319:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es.rb:352:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:159:in `buffer_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es.rb:312:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/outputs/base.rb:83:in `multi_receive'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/outputs/base.rb:83:in `multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/output_delegator.rb:130:in `worker_multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/output_delegator.rb:114:in `multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:301:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:301:in `output_batch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:232:in `worker_loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:201:in `start_workers'"], :level=>:error}

{:timestamp=>"2016-06-14T14:25:02.900000+0000", :message=>"Failed to flush outgoing items", :outgoing_count=>1, :exception=>"NoMethodError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.1.36/lib/aws-sdk-core/signers/v4.rb:24:in `initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es/aws_v4_signer_impl.rb:36:in `signer'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es/aws_v4_signer_impl.rb:48:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es/aws_transport.rb:49:in `perform_request'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.17/lib/elasticsearch/transport/transport/base.rb:257:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es/aws_transport.rb:45:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.17/lib/elasticsearch/transport/client.rb:128:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.17/lib/elasticsearch/api/actions/bulk.rb:88:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es/http_client.rb:53:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es.rb:322:in `submit'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es.rb:319:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es.rb:352:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:159:in `buffer_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.3-java/lib/logstash/outputs/amazon_es.rb:312:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/outputs/base.rb:83:in `multi_receive'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/outputs/base.rb:83:in `multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/output_delegator.rb:130:in `worker_multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/output_delegator.rb:114:in `multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:301:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:301:in `output_batch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:232:in `worker_loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:201:in `start_workers'"], :level=>:warn}

**Comment by catherinemarymorse** [comment]
I have also read up on this and it might be because you do not specify the aws_access_key and secret_access_key parameters in the plugin. You can read Val's comment here http://stackoverflow.com/questions/37785492/stream-data-to-amazon-elasticsearch-using-logstash where he mentions that even though those parameters are listed as optional in the readme file in the documentation for this plugin, there is a comment in the code saying that it is required for it to work (see comment here https://github.com/awslabs/logstash-output-amazon_es/blob/743e0dfec8655295abf84997ed4e32214c29f2b4/lib/logstash/outputs/amazon_es.rb#L116-L126)

**Comment by Lifang13** [comment]
I am having the same issue. 

I am using the plugin with version 1.0 and logstash 2.3.2

**Comment by sveba** [comment]
I have the same problem with the 1.5 version of ES on Amazon. With 2.3 the problem doesn't exist

**Comment by Lifang13** [comment]
@sveba  AWS ES currently only supports 1.5 , right?

**Comment by sveba** [comment]
Nope, 2.3 also

**Comment by sveba** [comment]
https://aws.amazon.com/releasenotes/Amazon-Elasticsearch-Service/0616801131960667

**Comment by Lifang13** [comment]
Awesome, do you happen to know how to upgrade it? Should I contact AWS support?

**Comment by sveba** [comment]
I cannot help you with upgrade, sorry.

**Comment by malpani** [comment]
@Lifang13 Here is the version migration strategy - http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-version-migration.html

We currently, do not support a direct upgrade, but insist on snapshot 1.5 - restore to 2.3 method as there are too many breaking changes and we do not want break existing clusters.

**Comment by mmutham** [comment]
We are using es 2.3 on aws elasticsearch and plugin logstash-output-amazon_es-1.0-java and are getting same exception and unable to push the data. 
We are able to push the data with curl though. In either approaches we are not passing credentials.

**Comment by lahirug** [comment]
Any of you were able to figure this out ? I am having the same error and kinda blocked due to this. Using ES 2.3.

**Comment by malpani** [comment]
To summarize:
`sudo /opt/logstash/bin/logstash -f /etc/logstash/conf.d/01-logstash.conf` - Works
`sudo service logstash start` - Errors

While, I am yet to figure why this could be happening. @lahirug are you able to work around by starting in non service mode?

**Comment by lahirug** [comment]
@malpani  Thanks for the response. I am using systemd unit in coreos I have no option of running logstash out of docker. I tried to run just docker still same issue. If i set the access keys etc should I set those in elastic search ? I have configured aws elastic search to give access to root iam which will allow anyone to push from that aws account.

**Comment by alongmuaz** [comment]
i'm also facing the same issues using command: bin/logstash -f db.conf .

**Comment by sonya** [comment]
@cpanato @Lifang13 @mmutham how/where are your credentials configured? I'm guessing this is happening because services don't have access to most environment variables...

**Comment by rodrigodelmonte** [comment]
I was also facing the same issue, seems that some dependency from the plugin need a aws credential, When I applied a Iam Role on the instance the problem stopped.

**Comment by cpanato** [comment]
I used a role profile, no keys were using for that.

**Comment by larsap** [comment]
Anyone got a solution to this? I've been trying every combination I can think of for this plugin version, logstash version and Elasticsearch 1.5 and 2.3, but all get the same error.

**Comment by Lifang13** [comment]
what is the error do you have when you curl to aws es endpoint

**Comment by malpani** [comment]
@larsap : like @sonya and @Lifang13 here mentioned, how are the credentials configured on your setup. Very likely this is because the services/user logstash is running as does not have access to the environment variables/default credential profiles.

This plugin relies on [AWS credential provider chain](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#using-the-default-credential-provider-chain) as invoked [here](https://github.com/awslabs/logstash-output-amazon_es/blob/master/lib/logstash/outputs/amazon_es/aws_transport.rb#L67)

**Comment by Lifang13** [comment]
for me, i have ` ~/.aws/credentials` with aws_access_key_id and aws_secret_access_key.  the plugin can use the credentials for access to aws

**Comment by larsap** [comment]
@Lifang13 @malpani Thanks for the quick feedback.

I finally figured out the error after I tried switching away from this plugin, and instead using the default logstash elasticsearch output with a source ip policy. I can't remember the error I got, but it lead me to believe that it was something wrong with my elasticsearch config. I had set "rest.action.multi.allow_explicit_index" to false, and by setting that to true pretty much made all the other errors go away. I do however now have to perform a slight refactoring on the input authentication part.

**Comment by UncertainSchrodinger** [comment]
I had a similar issue. Check the logs from the start to see if there are issues when loading the template. Mine was caused due to the machine clock drifting,  You'll get errors like "Signature not yet current"....

**Comment by tuapuikia** [comment]
I have the same issue, the logstash fail to start when using IAM credential from metadata.
I'm using plugin version 2.0.1 with AWS ES 5.1. 

[2017-10-06T03:19:11,307][ERROR][logstash.outputs.amazones] Failed to install template: undefined method `credentials' for nil:NilClass

My IAM instance policy is correct as I have no problem to access the ES with nodejs aws-es-proxy module.

**Comment by adikabintang** [comment]
@UncertainSchrodinger I have no "Signature not yet current" error, although I do have error loading template. What do you mean by "machine clock drifting"? Is it the kernel clock source that you switch to "tsc" (from "xen" for instance)?

**Comment by yair5124302** [comment]
I'm having the same problem using latest Logstash 6.2.4 running on Amazon Linux.
When I run logstash from command line it's working fine.
When I start logstash as a service using `sudo initctl logstash start` logs say service started successfully and no errors are seen but no data is sent to elasticsearch

**Comment by marcossv9** [comment]
Hello, I'm having same issue as @yair5124. 
When I run: `sudo /usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/apache.conf` works perfectly and logstash send logs to AWS ES.
When I run as a service using `sudo initctl logstash start` logstash starts correctly without errors but no data is sent to AWS ES.
This is really frustrating because we choose AWS ES instead of Elastic Cloud..
Currently we are running AWS ES v7.1, Kibana version 7.1.1 and Logstash version is 7.4 as the compatibility matrix says it supported [link](https://www.elastic.co/support/matrix#matrix_compatibility). Also we are sending data with Logstash from an Ubuntu 14.04.
Here are the two different outputs logs when running logstash from command and as a service:
[logstash_logs.log](https://github.com/awslabs/logstash-output-amazon_es/files/3692093/logstash_logs.log)

Any help would be appreciated.
Marcos.

**Comment by yair5124** [comment]
For me the problem was insufficient permission to read log files (docker container logs in my case).

I got it to work after running logstash process as root user.

**Comment by marcossv9** [comment]
> For me the problem was insufficient permission to read log files (docker container logs in my case).
> 
> I got it to work after running logstash process as root user.

Thanks for your comments @yair5124 . Sadly I'm also running the service as root user but anything changes. I will consider host my own ES instance without using the managed AWS ES Service due to issues.

**Comment by marcossv9** [comment]
Hi, I have found the issue:

The service starts with sudo but it runs under "logstash" user. So I had to add logstash user to group "adm" to be able to read the logs generated at "/var/log/apache2/*.log".

I used the command ```sudo usermod -a -G adm logstash```

Then I restarted the service and everything is working fine.

Thanks.
Marcos

**Comment by AustinTag** [comment]
Closing due to inactivity and likely resolution with newer versions. Please re-open if the problem persists.
