### ISSUE TITLE
logstash.outputs.amazones] Failed to flush outgoing items 

### ISSUE THREAD

**Issue by ChrisFernandez** [awslabs/logstash-output-amazon_es#57]
Hello using 
```
AWS elasticsearch 5.1
logstash 5.2.2-2
```
everything works if I fully open the permissions policy on ES. then I made it so the ec2 instance assumes a role that is allowed "fully" to speak to ES... so was not working.. then  I found out I needed to sent the token with the request etc this is when I found this plugin..
so I installed:
```
/usr/share/logstash/bin/logstash-plugin list | grep amazon_es
logstash-output-amazon_es
```

but I keep getting this in the logs.. :(

```
[2017-04-04T17:48:53,709][WARN ][logstash.outputs.amazones] Failed to flush outgoing items {:outgoing_count=>1, :exception=>"Elasticsearch::Transport::Transport::Errors::BadRequest", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/base.rb:318:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-2.0.1-java/lib/logstash/outputs/amazon_es/aws_transport.rb:48:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/client.rb:131:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-5.0.3/lib/elasticsearch/api/actions/bulk.rb:95:in `bulk'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-2.0.1-java/lib/logstash/outputs/amazon_es/http_client.rb:53:in `bulk'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-2.0.1-java/lib/logstash/outputs/amazon_es.rb:321:in `submit'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-2.0.1-java/lib/logstash/outputs/amazon_es.rb:318:in `submit'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-2.0.1-java/lib/logstash/outputs/amazon_es.rb:351:in `flush'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:159:in `buffer_receive'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-2.0.1-java/lib/logstash/outputs/amazon_es.rb:311:in `receive'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/legacy.rb:19:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:43:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:414:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:413:in `output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:371:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:331:in `start_workers'"]}
```

my config:

```
input {
  file { 
    path => ["/var/log/suricata/eve.json"]
    sincedb_path => ["/var/lib/logstash/since.db"]
    codec =>   json 
    type => "SuricataIDPS" 
  }

}

filter {
  if [type] == "SuricataIDPS" {
    date {
      match => [ "timestamp", "ISO8601" ]
    }
    #ruby {
    #  code => "if ['event_type'] == 'fileinfo'; event.set('[fileinfo][type]', event.set('[fileinfo][magic].to_s.split(',')[0]; end;')"
    #}
  }

  if [src_ip]  {
    geoip {
      source => "src_ip" 
      target => "geoip" 
      #database => "/etc/logstash/GeoLiteCity.dat" 
      #add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
      #add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}"  ]
    }
    mutate {
      convert => [ "[geoip][coordinates]", "float" ]
    }
    if ![geoip.ip] {
      if [dest_ip]  {
        geoip {
          source => "dest_ip" 
          target => "geoip" 
          #database => "/etc/logstash/GeoLiteCity.dat" 
          #add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
          #add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}"  ]
        }
        mutate {
          convert => [ "[geoip][coordinates]", "float" ]
        }
      }
    }
  }
}

output { 
  amazon_es {
    hosts => ["search-HERE_INSTANCE_NAME_ETC.us-east-1.es.amazonaws.com"]
    region => "us-east-1"
    index => "logstash-suricata-%{+YYYY.MM.dd}"
    template => "/etc/logstash/templates/suricata-template.json"
    template_overwrite => true
  }
}
```

I'm stuck on this and I do find similar issues but they are from 2-3 years a go, diff versions or diff configurations etc.. Any help will be appreciated

**Comment by ChrisFernandez** [comment]
ok I half fix this, I removed the ES:* block in the instance role so only the policy in the ES allowing that role is on... and I removed the explicit indexing option in ES... now I can at least create the indexing and does not bark... still no data is getting sent.. looking into that now,
