### ISSUE TITLE
Logstash instances all crash at the same time with the same error

### ISSUE THREAD

**Issue by majordhote** [awslabs/logstash-output-amazon_es#66]
Hi all,

We're using logstash as a GELF shipper to AWS ES.
Each of our instances receives its own traffic and thus generates its own logs.

All the logstash, from every instance, crash at the very same time with the following error:

> [2017-10-13T08:24:58,525][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<LogStash::Error: timestamp field is missing>, :backtrace=>["org/logstash/ext/JrubyEventExtLibrary.java:202:in `sprintf'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-2.0.1-java/lib/logstash/outputs/amazon_es.rb:302:in `receive'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/legacy.rb:22:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:47:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:420:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:419:in `output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:365:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:330:in `start_workers'"]}

Any idea or hint of what could be causing the problem?

Thank you very much for your support,
Regards.

**Comment by xyq164202** [comment]
Hi, we just release new version of our plugin can you try the new code to see if it resolve your issues? Thanks. Here is the link https://github.com/awslabs/logstash-output-amazon_es

**Comment by AustinTag** [comment]
Closing due to inactivity, please re-open if this issue still persists
