### ISSUE TITLE
Couldn't find any output plugin name amazon_es

### ISSUE THREAD

**Issue by seanoreilly1973** [awslabs/logstash-output-amazon_es#71]
I have just installed the plugin and it shows up in logstash-plugin list.

However when I restart logstash to pick up new configuration:

`output {
    amazon_es {
        hosts => ["vpc-endpoint.eu-west-2.es.amazonaws.com"]
        region => "eu-west-2"
        index  => "development-logs-%{+dd.MM.YYYY}"
    }
}`

I get the following error

`[2017-12-11T21:38:17,325][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::PluginLoadingError", :message=>"Couldn't find any output plugin named 'amazon_es'. Are you sure this is correct? Trying to load the amazon_es output plugin resulted in this error: Problems loading the requested plugin named amazon_es of type output. Error: NameError NameError", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/plugins/registry.rb:185:in `lookup_pipeline_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/plugin.rb:140:in `lookup'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:143:in `plugin'", "(eval):135:in `<eval>'", "org/jruby/RubyKernel.java:994:in `eval'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:82:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:215:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:35:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:335:in `block in converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:332:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:319:in `converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:362:in `block in execute'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]} `

Any help would be greatly appreciated.

**Comment by funbrain** [comment]
$logstash_HOME > bin > logstash-plugin list logstash-output 
if amazon_es  output plugin  not found in the list, then
$logstash_HOME > bin > logstash-plugin install logstash-output-amazon_es

**Comment by annaken** [comment]
I get the same error, yet I see the plugin listed as installed.

`$ /usr/share/logstash/bin/logstash-plugin list logstash-output
logstash-output-amazon_es`

`$ tail /var/log/logstash/logstash-plain.log
[2018-04-04T07:09:42,161][ERROR][logstash.agent           ] Cannot create pipeline {:reason=>"Couldn't find any output plugin named 'amazon_es'. Are you sure this is correct? Trying to load the amazon_es output plugin resulted in this error: Problems loading the requested plugin named amazon_es of type output. Error: NameError NameError"}`

Ubuntu 16, Logstash 5.6

**Comment by AustinTag** [comment]
Is this still an issue with the latest version?

**Comment by AustinTag** [comment]
Closing due to inactivity, please re-open if the issue persists with the latest versions
