### ISSUE TITLE
search-bbbbbb-1.es.amazonaws.com:443 failed to respond

### ISSUE THREAD

**Issue by funbrain** [awslabs/logstash-output-amazon_es#75]
does anybody know this issue?
[2018-01-24T08:43:04,967][ERROR][logstash.outputs.amazones] Attempted to send a bulk request to Elasticsearch configured at '["https://search-bbbbbb-.es.amazonaws.com:443"]', but an error occurred and it failed! Are you sure you can reach elasticsearch from this machine using the configuration provided? {:client_config=>{:hosts=>["https://search-bbbbbb-.es.amazonaws.com:443"], :region=>"ap-southeast-1", :transport_options=>{:request=>{:open_timeout=>0, :timeout=>60}, :proxy=>nil, :headers=>{"Content-Type"=>"application/json"}}, :transport_class=>Elasticsearch::Transport::Transport::HTTP::AWS}, :error_message=>"search-bbbbbb-.es.amazonaws.com:443 failed to respond", :error_class=>"Faraday::ClientError", :backtrace=>nil}
[2018-01-24T08:43:05,217][WARN ][logstash.outputs.amazones] Failed to flush outgoing items {:outgoing_count=>1, :exception=>"Faraday::ClientError", :backtrace=>nil}

**Comment by Sunduck** [comment]
same here

**Comment by louishe** [comment]
Who can solve it? Here too.

**Comment by marioluan** [comment]
Can you reach `search-bbbbbb-.es.amazonaws.com`?

**Comment by whuchenrui** [comment]
See the same issue randomly.  In most cases, logs can be successfully pushed to ElasticSearch. So the endpoint is reachable.  

    {:timestamp=>"2018-04-02T20:51:22.822000+0000", :message=>"Attempted to send a bulk request to Elasticsearch configured at '[\"https://fake_endpoint.es.amazonaws.com:443\"]', but an error occurred and it failed! Are you sure you can reach elasticsearch from this machine using the configuration provided?", :client_config=>{:hosts=>["https://fake_endpoint.es.amazonaws.com:443"], :region=>"us-east-1", :aws_access_key_id=>nil, :aws_secret_access_key=>nil, :aws_odin_material_set=>nil, :transport_options=> . {:request=>{:open_timeout=>0, :timeout=>60}, :proxy=>nil}, :transport_class=>Elasticsearch::Transport::Transport::HTTP::AWS, :logger=>nil, :tracer=>nil, :reload_connections=>false, :retry_on_failure=>false, :reload_on_failure=>false, :randomize_hosts=>false}, :error_message=>"fake_endpoint.es.amazonaws.com:443 failed to respond", :error_class=>"Faraday::ClientError", :backtrace=>nil, :level=>:error}
    {:timestamp=>"2018-04-02T20:51:22.824000+0000", :message=>"Failed to flush outgoing items", :outgoing_count=>1, :exception=>"Faraday::ClientError", :backtrace=>nil, :level=>:warn}

Btw, any suitable ways to track the data loss? Kind of worried about this error messages, though I checked one of my log files, I don't see any data loss

**Comment by brandonxsellco** [comment]
Any solution to this, having the same problem?

**Comment by Shypes** [comment]
`Attempted to send a bulk request to Elasticsearch configured at '["https://fake.eu-west-1.es.amazonaws.com:443"]', but an error occurred and it failed! Are you sure you can reach elasticsearch from this machine using the configuration provided? {:client_config=>{:hosts=>["https://fake.es.amazonaws.com:443"], :region=>"eu-west-1", :transport_options=>{:request=>{:open_timeout=>0, :timeout=>60}, :proxy=>nil}, :transport_class=>Elasticsearch::Transport::Transport::HTTP::AWS}, :error_message=>"fake.eu-west-1.es.amazonaws.com:443 failed to respond", :error_class=>"Faraday::ClientError", :backtrace=>nil, :level=>:error}`

**Comment by Shypes** [comment]
Hello xyq164202 ,
I just tried the new version, am getting a different error,


```Pipeline aborted due to error {:exception=>"URI::InvalidComponentError", :error=>"bad component(expected port component): 443", :backtrace=>["/opt/logstash/vendor/jruby/lib/ruby/1.9/uri/generic.rb:697:in `check_port'", "/opt/logstash/vendor/jruby/lib/ruby/1.9/uri/generic.rb:744:in `port='", "/opt/logstash/vendor/jruby/lib/ruby/1.9/uri/generic.rb:195:in `initialize'", "/opt/logstash/vendor/jruby/lib/ruby/1.9/uri/http.rb:84:in `initialize'",```

**Comment by xyq164202** [comment]
Document types are being deprecated in Elasticsearch 6.0, try not set document_type in your config

**Comment by xyq164202** [comment]
Hi, May I ask what's your ES version

**Comment by xyq164202** [comment]
Hello Shypes:
Would you please upgrade your logstash to the newest version(6.4.0) and try again?
Thanks!

**Comment by Shypes** [comment]
Hi xyq164202, sure i would upgrade and give it a try

My current Elastic Search running on ec2 instance is version 2.4.6.

Managed version of Elastic Search to migrate to is 2.3. but thinking i should make the managed elasticsearch 6.0* right now.

I have currently shut down the managed Elastic Search, i would need to set it up and test.

**Comment by xyq164202** [comment]
Hi Shypes :
Remember use the newest Logstash version too.

**Comment by jsanjay63** [comment]
facing the same issue/error when executing this with logstash docker

**Comment by xyq164202** [comment]
> facing the same issue/error when executing this with logstash docker

Hi jsanjay63:
    This issue can be fixed with updated Logstash version to 6.4.0. Thanks

**Comment by AustinTag** [comment]
Closing due to inactivity, please re-open if the issue persists with the latest versions
