### ISSUE TITLE
Logstash exits instantly with new version of this plugin

### ISSUE THREAD

**Issue by chriser-** [awslabs/logstash-output-amazon_es#99]
The newest version (6.4.0) causes our logstash (5.6.8, dockerized) to exit immediately after installing the plugin with the following error.
```
ERROR logstash.pipeline - Error registering plugin {
	: plugin=>"#<LogStash::OutputDelegator:0x3c61134f @namespaced_metric=#<LogStash::Instrument::NamespacedMetric:0x579596f7 @metric=#<LogStash::Instrument::Metric:0x7fd3e49f @collector=#<LogStash::Instrument::Collector:0x4aef2e5b @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x7e20a722 @store=#<Concurrent::Map:0x0000000006646c entries=2 default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x579b43f>, @fast_lookup=#<Concurrent::Map:0x00000000066470 entries=113 default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs, :\"a5356296317869bdf0a59ef89364415531675b01-17\"]>, @metric=#<LogStash::Instrument::NamespacedMetric:0x56402813 @metric=#<LogStash::Instrument::Metric:0x7fd3e49f @collector=#<LogStash::Instrument::Collector:0x4aef2e5b @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x7e20a722 @store=#<Concurrent::Map:0x0000000006646c entries=2 default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x579b43f>, @fast_lookup=#<Concurrent::Map:0x00000000066470 entries=113 default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs]>, @logger=#<LogStash::Logging::Logger:0x65320d89 @logger=#<Java::OrgApacheLoggingLog4jCore::Logger:0x7c8ff6b9>>, @out_counter=LogStash::Instrument::MetricType::Counter - namespaces: [:stats, :pipelines, :main, :plugins, :outputs, :\"a5356296317869bdf0a59ef89364415531675b01-17\", :events] key: out value: 0, @in_counter=LogStash::Instrument::MetricType::Counter - namespaces: [:stats, :pipelines, :main, :plugins, :outputs, :\"a5356296317869bdf0a59ef89364415531675b01-17\", :events] key: in value: 0, @strategy=#<LogStash::OutputDelegatorStrategies::Shared:0x1c9dc610 @output=<LogStash::Outputs::ElasticSearch hosts=>[//<removed>.us-east-1.es.amazonaws.com], index=>\"logstash-%{+YYYY.MM.dd}\", region=>\"us-east-1\", aws_access_key_id=>\"<removed>\", aws_secret_access_key=>\"<removed>\", id=>\"a5356296317869bdf0a59ef89364415531675b01-17\", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>\"plain_0e072b6c-81f1-439c-8c97-3c5f9ddf9d3d\", enable_metric=>true, charset=>\"UTF-8\">, workers=>1, manage_template=>true, template_name=>\"logstash\", template_overwrite=>false, doc_as_upsert=>false, script_type=>\"inline\", script_lang=>\"painless\", script_var_name=>\"event\", scripted_upsert=>false, retry_initial_interval=>2, retry_max_interval=>64, retry_on_conflict=>1, action=>\"index\", port=>443, protocol=>\"https\", ssl_certificate_verification=>true, sniffing=>false, sniffing_delay=>5, timeout=>60, pool_max=>1000, pool_max_per_route=>100, resurrect_delay=>5, validate_after_inactivity=>10000, http_compression=>false, metric=>#<LogStash::Instrument::NamespacedMetric:0x579596f7 @metric=#<LogStash::Instrument::Metric:0x7fd3e49f @collector=#<LogStash::Instrument::Collector:0x4aef2e5b @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x7e20a722 @store=#<Concurrent::Map:0x0000000006646c entries=2 default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x579b43f>, @fast_lookup=#<Concurrent::Map:0x00000000066470 entries=113 default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs, :\"a5356296317869bdf0a59ef89364415531675b01-17\"]>>>, @id=\"a5356296317869bdf0a59ef89364415531675b01-17\", @time_metric=LogStash::Instrument::MetricType::Counter - namespaces: [:stats, :pipelines, :main, :plugins, :outputs, :\"a5356296317869bdf0a59ef89364415531675b01-17\", :events] key: duration_in_millis value: 0, @metric_events=#<LogStash::Instrument::NamespacedMetric:0x6936ce4f @metric=#<LogStash::Instrument::Metric:0x7fd3e49f @collector=#<LogStash::Instrument::Collector:0x4aef2e5b @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x7e20a722 @store=#<Concurrent::Map:0x0000000006646c entries=2 default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x579b43f>, @fast_lookup=#<Concurrent::Map:0x00000000066470 entries=113 default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs, :\"a5356296317869bdf0a59ef89364415531675b01-17\", :events]>, @output_class=LogStash::Outputs::ElasticSearch>",
	: error=>"bad component(expected port component): 443"
}
ERROR logstash.agent - Pipeline aborted due to error {
	: exception=>#<URI: : InvalidComponentError: badcomponent(expectedportcomponent): 443>,
	: backtrace=>[
        "/usr/share/logstash/vendor/jruby/lib/ruby/1.9/uri/generic.rb:697:in `check_port'",
	"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/uri/generic.rb:744:in `port='",
	"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/uri/generic.rb:195:in `initialize'",
	"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/uri/http.rb:84:in `initialize'",
	"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/uri/generic.rb:140:in `build'",
	"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/uri/http.rb:62:in `build'",
	"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client/manticore_adapter.rb:96:in `perform_request'",
	"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client/pool.rb:291:in `perform_request_to_url'",
	"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client/pool.rb:245:in `healthcheck!'",
	"org/jruby/RubyHash.java:1342:in `each'",
	"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client/pool.rb:241:in `healthcheck!'",
	"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client/pool.rb:341:in `update_urls'",
	"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client/pool.rb:71:in `start'",
	"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client.rb:316:in `build_pool'",
	"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client.rb:66:in `initialize'",
	"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client_builder.rb:108:in `create_http_client'",
	"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/http_client_builder.rb:98:in `build'",
	"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es.rb:253:in `build_client'",
	"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-6.4.0-java/lib/logstash/outputs/amazon_es/common.rb:25:in `register'",
	"/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:9:in `register'",
	"/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:43:in `register'",
	"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:290:in `register_plugin'",
	"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:301:in `register_plugins'",
	"org/jruby/RubyArray.java:1613:in `each'",
	"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:301:in `register_plugins'",
	"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:310:in `start_workers'",
	"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:235:in `run'",
	"/usr/share/logstash/logstash-core/lib/logstash/agent.rb:408:in `start_pipeline'"]
}
INFO  logstash.agent - Successfully started Logstash API endpoint {:port=>9600}
WARN  logstash.agent - stopping pipeline {:id=>"main"}
FATAL logstash.runner - An unexpected error occurred! {
	: error=>#<NoMethodError: undefinedmethod`call'fornil: NilClass>,
	: backtrace=>[
        "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-redis-3.1.6/lib/logstash/inputs/redis.rb:100:in `stop'",
	"/usr/share/logstash/logstash-core/lib/logstash/inputs/base.rb:89:in `do_stop'",
	"org/jruby/RubyArray.java:1613:in `each'",
	"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:513:in `shutdown'",
	"/usr/share/logstash/logstash-core/lib/logstash/agent.rb:436:in `stop_pipeline'",
	"/usr/share/logstash/logstash-core/lib/logstash/agent.rb:452:in `shutdown_pipelines'",
	"org/jruby/RubyHash.java:1342:in `each'",
	"/usr/share/logstash/logstash-core/lib/logstash/agent.rb:452:in `shutdown_pipelines'",
	"/usr/share/logstash/logstash-core/lib/logstash/agent.rb:139:in `shutdown'",
	"/usr/share/logstash/logstash-core/lib/logstash/runner.rb:328:in `execute'",
	"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'",
	"/usr/share/logstash/logstash-core/lib/logstash/runner.rb:204:in `run'",
	"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'",
	"/usr/share/logstash/lib/bootstrap/environment.rb:71:in `(root)'"]
}
```

the plugin is configures as follows:
```
  amazon_es {
      hosts => ["<removed>.us-east-1.es.amazonaws.com"]
      index => "logstash-%{+YYYY.MM.dd}"
      region => "us-east-1"
      aws_access_key_id => "<removed>"
      aws_secret_access_key => "<removed>"
  }
```
Version 6.0.0 works without problems.
Don't hesitate to ask if you need additional details.

**Comment by Puneeth-n** [comment]
@chriser- Faced the same issue. Had to roll back to 6.0.0

**Comment by xyq164202** [comment]
Hi: may I ask your ES and Logstash Version? For temporally use, you can install 6.0.0 version in logstash directory with this command line:
bin/logstash-plugin install logstash-output-amazon_es -v 6.0.0

**Comment by xyq164202** [comment]
Hello Chriser:
Would you please upgrade your logstash to the newest version(6.4.0) and try again?
Thanks!

**Comment by chriser-** [comment]
Hi, sorry for the late reply.
ES is running on 5.5, logstash (as said above) 5.6.8.
Also, 6.0.0 runs fine, I installed it before I posted this issue with the same command you provided.

If your permanent solution is to leave logstash 5.x working with <6.0 and keep >6.0 only for logstash 6.x, you can resolve this issue.
As our solution (ES 5.5, logstash 5.6.8, amazon_es plugin 6.0.0) is running fine with no issues, I have no intention to change that setup.

**Comment by xyq164202** [comment]
Hi chriser:
For logstash version earlier than 6.0, I will recommend you still use amazon_es plugin 6.0.0, it should works fine. However, I will suggest you upgrade logstash to the newest version and use or plugin 6.4, it has better performance and more new features. You don't need to upgrade your ES by the way.

**Comment by crisidev** [comment]
Is this still an issue folks?

**Comment by AustinTag** [comment]
Closing due to inactivity, please re-open if the issue persists with the latest versions
